name: FacialRecognition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - ipykernel
  - jupyter
  - pillow
  - opencv
  - scipy
  - tornado
  - traitlets
  - zlib
  - xz
  - libffi
  - tk
  - setuptools
  - psutil
  - typing-extensions
  - pygments
  - jupyter_client
  - jupyter_core
  - traitlets
  - typing-extensions
  - stack_data
  - prompt-toolkit
  - jedi
  - matplotlib-inline
  - platformdirs
  - tornado
  - wcwidth
  - six
  - decorator
  - debugpy
  - importlib-metadata
  - typing_extensions
  - nest-asyncio
  - parso
  - packaging
  - pickleshare
  - zipp
  - pyzmq
  - pip:
      - opencv-python
      - contourpy
      - cycler
      - fonttools
      - joblib
      - kiwisolver
      - threadpoolctl
      - pytz
      - tzdata
